### ISSUE TITLE
Action - Build and test = auto-run check and stop on error

### ISSUE THREAD

**Issue by SteveLLamb** [ISDCF/registries-site#11]
@palemieux @radford-for-smpte 

The merge of `registeries` today caused an error with the auto build (Incompatible registry schema: http://isdcf.com/ns/json-schemas/registries/... ) However, for some reason when I look at all the auto builds, they ran and reported no issues. 

So firstly, we need to see why it didn't flag (when building locally did). 

Then we need to add some type of "stop build and don't overwrite" on error

**Comment by radford-for-smpte** [comment]
If you look in the output of the scheduled "build and test", can see the error under "Run npm run build":

https://github.com/ISDCF/registries-site/runs/982419686?check_suite_focus=true

The problem I believe in here:

https://github.com/ISDCF/registries-site/blob/2e94fb6b592a5706262309613255d1819d445586/src/main/scripts/build.js#L237

This line is turning exceptions into console.errors(). Thus the process isn't returning a non-zero exit code.

**Comment by SteveLLamb** [comment]
Ah, yes, I see that now. I’ll update while getting the new fields added to the templates.
