### ISSUE TITLE
Move isdcf.github.io pages under the isdcf.com domain

### ISSUE THREAD

**Issue by radford-for-smpte** [ISDCF/registries-site#22]
We currently host the JSON registry on `registry.isdcf.com`. It would be great to establish an equivalent for the HTML version which is currently hosted on isdcf.github.io.

* Establish `site.registry.isdcf.com` (or something similar) 

See: https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site

**Comment by palemieux** [comment]
@SteveLLamb Let me know if/when you want to make the switch

**Comment by SteveLLamb** [comment]
To keep in line with current naming and structure of the ISDCF site I would suggest this to be (to make easy bookmarks and for integration of the ISDCF registry section in the future):

Current webpages: https://www.isdcf.com/site/dcnc-appendix-1ab-language-codes/
Registries example (current): https://registry.isdcf.com/languages
**Rendered pages from registries (proposed): https://page.registry.isdcf.com/languages**

**Comment by radford-for-smpte** [comment]
I'd be good w/ that. Or how about https://registry-page.isdcf.com/ ?

My concern with "page" is that we already use the word "site" in the GitHub repo to imply a browsable HTML page. @palemieux  what do you think?

**Comment by SteveLLamb** [comment]
I like the hyphenated version you propose. I want to stay away from site, as that is the structure of the ISDCF site itself, to make it clear it's not in there directly. If that makes sense?

**Comment by radford-for-smpte** [comment]
@SteveLLamb that URL isn't working for me:

  https://registry-page.isdcf.com

Getting a GitHub 404.

**Comment by SteveLLamb** [comment]
> @SteveLLamb that URL isn't working for me:
> 
> https://registry-page.isdcf.com
> 
> Getting a GitHub 404.

It was working before the PR closed. We’re waiting to see if the CNAME is taking time to resolve.

**Comment by palemieux** [comment]
Working now.

https://registry-page.isdcf.com/facilities.html
https://registry-page.isdcf.com/languages.html
https://registry-page.isdcf.com/studios.html
