### ISSUE TITLE
HTML doesn't pass W3C validator

### ISSUE THREAD

**Issue by radford-for-smpte** [ISDCF/registries-site#33]
See: https://validator.w3.org/nu/?doc=https%3A%2F%2Fregistry-page.isdcf.com%2Ffacilities.html

**Comment by SteveLLamb** [comment]
Updating to new folder structure: https://validator.w3.org/nu/?doc=https%3A%2F%2Fregistry-page.isdcf.com%2Ffacilities%2Findex.html

**Comment by SteveLLamb** [comment]
@radford-for-smpte sorry, totally missed this issue being added during the huge push. This is now ready for review in #45
