### ISSUE TITLE
Add support for studios and language registries

### ISSUE THREAD

**Issue by palemieux** [ISDCF/registries-site#4]
See https://github.com/ISDCF/registries/pull/28

**Comment by radford-for-smpte** [comment]
@SteveLLamb if you're working on this, you might want to grab the existing [template](https://github.com/sandflow/melt/blob/master/templates/isdcf.hbs) for the `languages` page. Or let me know if you want me to help.

**Comment by SteveLLamb** [comment]
> @SteveLLamb if you're working on this, you might want to grab the existing [template](https://github.com/sandflow/melt/blob/master/templates/isdcf.hbs) for the `languages` page. Or let me know if you want me to help.

@radford-for-smpte I'll try to jump on this tomorrow. I'm going to use the facilities template as the base, as there was a lot of customizing I did for mobile and proper anchoring. I'll refer to the template you linked for the proper values to look for. Thanks!
