### ISSUE TITLE
Terminology Link

### ISSUE THREAD

**Issue by japierce1028** [ISDCF/registries-site#76]
Can we add a link to the terminology page to accept new / modified submissions? Here is a candidate link: Terminology Registry
https://docs.google.com/forms/d/e/1FAIpQLSeXgkHAp15nX3KOhrKMQYImUxCggajLpBpktr0d6H0zE-i3AA/viewform?usp=pp_url

**Comment by SteveLLamb** [comment]
Also moved this over to the site repo, as it will be added to https://github.com/ISDCF/registries-site/pulls

**Comment by SteveLLamb** [comment]
Closed via https://github.com/ISDCF/registries-site/pull/75
